import { View, Text, StyleSheet, FlatList, ScrollView, ActivityIndicator, TouchableOpacity, Alert, Linking, Share } from 'react-native';
import { useStore } from '../store/useStore';
import { colors } from '../theme/colors';
import * as Queries from '../db/queries';

export default function ReportsScreen() {
  const db = useStore(state => state.db);
  const [dailySales, setDailySales] = useState([]);
  const [loading, setLoading] = useState(true);
  
  const totalSalesAllTime = dailySales.reduce((sum, day) => sum + (day.total_sales || 0), 0);
  const totalCashSales = dailySales.reduce((sum, day) => sum + (day.cash_sales || 0), 0);
  const totalBankSales = dailySales.reduce((sum, day) => sum + (day.bank_sales || 0), 0);
  const totalCreditSales = dailySales.reduce((sum, day) => sum + (day.credit_sales || 0), 0);
  const totalGrossProfit = dailySales.reduce((sum, day) => sum + (day.gross_profit || 0), 0);
  const totalLossAllTime = dailySales.reduce((sum, day) => sum + (day.total_loss || 0), 0);
  const totalNetProfit = totalGrossProfit - totalLossAllTime;

  const shopProfile = useStore(state => state.shopProfile);

  useEffect(() => {
    const fetchReports = async () => {
      if (db) {
        setLoading(true);
        try {
          const sales = await Queries.getDailySales(db);
          setDailySales(sales);
        } catch (e) {
          console.error('Fetch reports error:', e);
        } finally {
          setLoading(false);
        }
      }
    };
    fetchReports();
  }, [db]);

  const shareSummary = async (type) => {
    let title = "";
    let sales = 0;
    let profit = 0;
    let bank = 0;
    let cash = 0;
    let credit = 0;

    if (type === 'Today' && dailySales.length > 0) {
      const today = dailySales[0];
      title = `Daily Summary (${today.date})`;
      sales = today.total_sales;
      profit = today.net_profit;
      bank = today.bank_sales;
      cash = today.cash_sales;
      credit = today.credit_sales;
    } else if (type === 'Weekly') {
      const last7 = dailySales.slice(0, 7);
      title = "Weekly Summary (Last 7 Days)";
      sales = last7.reduce((s, h) => s + (h.total_sales || 0), 0);
      profit = last7.reduce((s, h) => s + (h.net_profit || 0), 0);
      bank = last7.reduce((s, h) => s + (h.bank_sales || 0), 0);
      cash = last7.reduce((s, h) => s + (h.cash_sales || 0), 0);
      credit = last7.reduce((s, h) => s + (h.credit_sales || 0), 0);
    } else if (type === 'Monthly') {
      title = "Monthly Summary (Last 30 Days)";
      sales = totalSalesAllTime;
      profit = totalNetProfit;
      bank = totalBankSales;
      cash = totalCashSales;
      credit = totalCreditSales;
    }

    const message = `📊 *${shopProfile?.shop_name || 'Stock App'} - ${title}*\n\n` +
      `💰 Total Sales: ₹${sales.toFixed(2)}\n` +
      `📈 Net Profit: ₹${profit.toFixed(2)}\n\n` +
      `*Payment Breakdown:*\n` +
      `💵 Cash: ₹${cash.toFixed(2)}\n` +
      `🏦 Bank: ₹${bank.toFixed(2)}\n` +
      `💳 Credit: ₹${credit.toFixed(2)}\n\n` +
      `Generated by Stock App`;

    try {
      await Share.share({ message });
    } catch (error) {
      Alert.alert('Error', 'Failed to share summary');
    }
  };

  const renderItem = ({ item }) => (
    <View style={styles.row}>
      <View style={{ flex: 1.2 }}>
        <Text style={styles.cellDate}>{item.date}</Text>
        <Text style={styles.cellSubText}>Sales: ₹{item.total_sales?.toFixed(2)}</Text>
      </View>
      <View style={styles.cellGroup}>
        <View style={styles.paymentPills}>
          {item.cash_sales > 0 && <View style={[styles.pill, {backgroundColor: '#E6F4EA'}]}><Text style={[styles.pillText, {color: '#1E7E34'}]}>C</Text></View>}
          {item.bank_sales > 0 && <View style={[styles.pill, {backgroundColor: '#E8F0FE'}]}><Text style={[styles.pillText, {color: '#1967D2'}]}>B</Text></View>}
          {item.credit_sales > 0 && <View style={[styles.pill, {backgroundColor: '#FEF1F1'}]}><Text style={[styles.pillText, {color: '#D93025'}]}>Cr</Text></View>}
        </View>
        <Text style={[styles.cellProfit, { color: item.net_profit >= 0 ? colors.secondary : colors.danger }]}>
          ₹{item.net_profit?.toFixed(2)}
        </Text>
      </View>
    </View>
  );

  if (loading) {
    return (
      <View style={[styles.container, { justifyContent: 'center' }]}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <ScrollView>
        <View style={styles.summaryCard}>
          <Text style={styles.summaryTitle}>Overall Performance (Net)</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryBox}>
              <Text style={styles.summaryLabel}>Total Sales</Text>
              <Text style={styles.summaryValue}>₹{totalSalesAllTime.toFixed(2)}</Text>
            </View>
            <View style={[styles.summaryBox, { borderLeftWidth: 1, borderColor: colors.border }]}>
              <Text style={styles.summaryLabel}>Net Profit</Text>
              <Text style={[styles.summaryValue, { color: totalNetProfit >= 0 ? colors.secondary : colors.danger }]}>
                ₹{totalNetProfit.toFixed(2)}
              </Text>
            </View>
          </View>

          <View style={styles.paymentSummary}>
            <View style={styles.paymentBox}>
              <Text style={styles.paymentLabel}>Cash</Text>
              <Text style={styles.paymentValue}>₹{totalCashSales.toFixed(2)}</Text>
            </View>
            <View style={styles.paymentBox}>
              <Text style={styles.paymentLabel}>Bank</Text>
              <Text style={styles.paymentValue}>₹{totalBankSales.toFixed(2)}</Text>
            </View>
            <View style={styles.paymentBox}>
              <Text style={styles.paymentLabel}>Credit</Text>
              <Text style={styles.paymentValue}>₹{totalCreditSales.toFixed(2)}</Text>
            </View>
          </View>
          
          <View style={styles.detailSummary}>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Gross Profit:</Text>
              <Text style={styles.detailValue}>+ ₹{totalGrossProfit.toFixed(2)}</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Loss (Deductions):</Text>
              <Text style={[styles.detailValue, { color: colors.danger }]}>- ₹{totalLossAllTime.toFixed(2)}</Text>
            </View>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Share Reports</Text>
        <View style={styles.shareRow}>
          <TouchableOpacity style={styles.shareBtn} onPress={() => shareSummary('Today')}>
            <Text style={styles.shareBtnIcon}>📅</Text>
            <Text style={styles.shareBtnText}>Today</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.shareBtn} onPress={() => shareSummary('Weekly')}>
            <Text style={styles.shareBtnIcon}>🗓️</Text>
            <Text style={styles.shareBtnText}>Weekly</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.shareBtn} onPress={() => shareSummary('Monthly')}>
            <Text style={styles.shareBtnIcon}>📊</Text>
            <Text style={styles.shareBtnText}>Monthly</Text>
          </TouchableOpacity>
        </View>

        <Text style={styles.sectionTitle}>Daily Performance</Text>
        
        <FlatList
          data={dailySales}
          keyExtractor={(item, index) => index.toString()}
          renderItem={renderItem}
          scrollEnabled={false}
          ListEmptyComponent={
            <View style={styles.emptyContainer}>
              <Text style={styles.emptyText}>No sales or deduction data available yet.</Text>
            </View>
          }
        />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, padding: 16, paddingBottom: 40 },
  summaryCard: {
    backgroundColor: colors.surface, borderRadius: 16, padding: 20,
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05, shadowRadius: 10, elevation: 2, marginBottom: 24,
  },
  summaryTitle: { fontSize: 16, fontWeight: 'bold', color: colors.textLight, marginBottom: 16, textAlign: 'center' },
  summaryGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  summaryBox: { flex: 1, alignItems: 'center' },
  summaryLabel: { fontSize: 13, color: colors.textLight, marginBottom: 4 },
  summaryValue: { fontSize: 24, fontWeight: 'bold', color: colors.primary },
  
  detailSummary: { borderTopWidth: 1, borderColor: colors.border, paddingTop: 16 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  detailLabel: { fontSize: 13, color: colors.textLight },
  detailValue: { fontSize: 13, fontWeight: 'bold', color: colors.secondary },

  paymentSummary: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  paymentBox: { flex: 1, backgroundColor: colors.background, padding: 8, borderRadius: 8, alignItems: 'center' },
  paymentLabel: { fontSize: 11, color: colors.textLight, marginBottom: 2 },
  paymentValue: { fontSize: 14, fontWeight: 'bold', color: colors.text },

  shareRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  shareBtn: { flex: 1, backgroundColor: colors.surface, padding: 12, borderRadius: 12, alignItems: 'center', elevation: 2 },
  shareBtnIcon: { fontSize: 20, marginBottom: 4 },
  shareBtnText: { fontSize: 12, fontWeight: 'bold', color: colors.primary },

  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: colors.text, marginBottom: 16 },
  row: {
    backgroundColor: colors.surface, padding: 16, borderRadius: 12, marginBottom: 12,
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 5, elevation: 1,
  },
  cellDate: { fontSize: 14, fontWeight: 'bold', color: colors.text },
  cellSubText: { fontSize: 11, color: colors.textLight, marginTop: 2 },
  cellGroup: { alignItems: 'flex-end' },
  cellProfit: { fontSize: 16, fontWeight: 'bold', marginTop: 4 },
  paymentPills: { flexDirection: 'row', gap: 4 },
  pill: { minWidth: 20, height: 20, borderRadius: 10, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 4 },
  pillText: { fontSize: 9, fontWeight: 'bold' },
  
  emptyContainer: { backgroundColor: colors.surface, padding: 40, borderRadius: 12, alignItems: 'center' },
  emptyText: { textAlign: 'center', color: colors.textLight, fontSize: 14 },
});
